### ISSUE TITLE
plays any file

### ISSUE THREAD

**Issue by vanderheyde** [cfinke/Channel-Two#3]
I'm noticing that it loads any file in the directories. This includes srt subtitles or even the thumbs.db files. the screen is just black with the notification of 'you're watching...'
![image](https://user-images.githubusercontent.com/8624868/219778756-42a5fdc8-04be-4c27-8665-f9263d85e0da.png)

Is there an option to include or exclude certain filetypes in the scan?

thanks!

**Comment by cfinke** [comment]
I've fixed this by checking mime types before adding files to the schedule, but I would have thought it would have immediately went on to the next file when the playback failed, so I'll look into why that didn't happen too.
