### ISSUE TITLE
Shuffle=false new episode behavior

### ISSUE THREAD

**Issue by memmam** [cfinke/Channel-Two#4]
I'd like to be able to run a show multiple times a week, but for it to only switch to a new episode after the full week has passed (e.g. play the same episode Monday-Friday, but then advance to the next episode the following Monday).

I'm guessing (haven't tried yet) that I can approximate this by having lines of the format

```
0 8 * * 1 /path/to/show
0 8 * * 2 /path/to/show
0 8 * * 3 /path/to/show
0 8 * * 4 /path/to/show
0 8 * * 5 /path/to/show
```

but it'd be nice to be able to consolidate it into a single line

**Comment by cfinke** [comment]
You could consolidate those lines to this:

```0 8 * * 1-5 /path/to/show```

but unless `/path/to/show` is a single video file or a directory with just one file in it, it will still play the next episode each day. I think the only way to play the same episode every day for a week and then change episodes after that is to have a separate process that ensures that `/path/to/show` is a single file (or a directory with just one file in it ) and manually swap it out with the new episode when you want it to change.

**Comment by memmam** [comment]
Consider this a feature request, then. My seemingly naive hope was that doing five entries instead of `1-5` would create five 'instances' of the show, each with their own episode queue. I'm trying to mimic the behavior of some TV stations where, if they premiered a new episode of a show, they would run it multiple times that week in case someone missed the day it premiered.

**Comment by cfinke** [comment]
Actually, I think you were correct and I was wrong -- I was not thinking about how each different scheduling line gets its own playback history, so your original solution should work.
